# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up dotnet core sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1' 
      - name: Run test
        run:
          dotnet test
      - name: Run build
        run:  
          dotnet build -c Release
      - name: Publish to nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Wwbweibo.Utils/Wwbweibo.Utils.csproj
          NUGET_KEY: ${{secrets.NUGET_PUSH_TOKEN}} 
